### ISSUE TITLE
Any progress of reproduced the results in the paper?

### ISSUE THREAD

**Issue by circlehy** [gupta-abhay/pytorch-frn#10]
Hi, good work, any progress of reproduced the results in the paper? Thank you.

**Comment by gupta-abhay** [comment]
Yes. I was able to get it working for regular ImageNet classification. Not able to reproduce the results in the paper. Working on that part as of now.

**Comment by ppwwyyxx** [comment]
FYI: https://github.com/ppwwyyxx/FRN-on-common-ImageNet-baseline

**Comment by gupta-abhay** [comment]
Thanks for letting me know.
