### ISSUE TITLE
Docstring for tau missing

### ISSUE THREAD

**Issue by rasbt** [gupta-abhay/pytorch-frn#2]
Thanks for sharing the implementation. Just a quick note: Looks like you didn't mention the threshold tau in your docstring.

**Comment by gupta-abhay** [comment]
do you mean something like in line 9 - which has beta, gamma and tau mentioned having shapes [1,C,1,1] ?

**Comment by rasbt** [comment]
yes exactly! Just see that you fixed it. Thx
