### ISSUE TITLE
Is it only for 2D images? 

### ISSUE THREAD

**Issue by xuzhang5788** [gupta-abhay/pytorch-frn#4]
Can it be used for 3D convolutional NN models? It will be great if you also have a keras or tf.keras impletation? 
Many thanks.

**Comment by gupta-abhay** [comment]
the original paper has a tf implementation - which will work directly when you use tf.keras models.

for 3D conv models - you can do something like this
<img width="654" alt="Screen Shot 2019-12-03 at 6 27 43 PM" src="https://user-images.githubusercontent.com/8841427/70098678-b02d7d80-15fa-11ea-8dd4-3bce12903de7.png">

**Comment by xuzhang5788** [comment]
Thank you very much!
